import { InstallmentCalculatorInput, InstallmentDetail } from '../../types/installment';

/**
 * Distributes a total amount (in cents) across a given number of parts
 * using floor division. The remainder is added to the first parcel.
 *
 * @param total - Total amount in cents (integer)
 * @param parts - Number of parts to distribute into
 * @returns Array of amounts in cents, where sum equals total exactly
 */
export function distributeAmount(total: number, parts: number): number[] {
  const base = Math.floor(total / parts);
  const remainder = total - base * parts;

  const result: number[] = new Array(parts);
  result[0] = base + remainder;
  for (let i = 1; i < parts; i++) {
    result[i] = base;
  }

  return result;
}

/**
 * Advances a month string (YYYY-MM) by a given offset.
 * Handles year rollover correctly (e.g., 2025-12 + 1 = 2026-01).
 *
 * @param month - Start month in YYYY-MM format
 * @param offset - Number of months to advance (0-based, so 0 returns the same month)
 * @returns Month string in YYYY-MM format
 */
export function advanceMonth(month: string, offset: number): string {
  const [yearStr, monthStr] = month.split('-');
  const year = parseInt(yearStr ?? '0', 10);
  const m = parseInt(monthStr ?? '1', 10);

  // Total months from epoch-like reference (0-indexed internally)
  const totalMonths = year * 12 + (m - 1) + offset;
  const newYear = Math.floor(totalMonths / 12);
  const newMonth = (totalMonths % 12) + 1;

  return `${newYear}-${String(newMonth).padStart(2, '0')}`;
}

/**
 * Calculates installment details combining amount distribution,
 * month advancement, and description suffix generation.
 *
 * The descriptionSuffix is generated by appending the parcel indicator
 * to the title (e.g., "Supermercado (1/3)").
 *
 * @param input - Calculator input with totalAmount, parcelCount, startMonth, title, etc.
 * @returns Array of InstallmentDetail objects for each parcel
 */
export function calculateInstallments(input: InstallmentCalculatorInput): InstallmentDetail[] {
  const { totalAmount, parcelCount, startMonth, title } = input;

  const amounts = distributeAmount(totalAmount, parcelCount);

  const installments: InstallmentDetail[] = [];

  for (let i = 0; i < parcelCount; i++) {
    const suffix = ` (${i + 1}/${parcelCount})`;
    const amount = amounts[i];
    if (amount !== undefined) {
      installments.push({
        index: i + 1,
        totalParcels: parcelCount,
        amount,
        referenceMonth: advanceMonth(startMonth, i),
        descriptionSuffix: title ? `${title}${suffix}` : suffix,
      });
    }
  }

  return installments;
}
